---
apiVersion: v1
kind: Service
metadata:
  name: openmrs-svc
spec:
  type: LoadBalancer
  selector:
    app: openmrs
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: openmrsport
